# front_adso-main/nginx.conf
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Configuración para aplicaciones SPA (Single Page Application)
    # Si el archivo o directorio no existe, sirve el index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuración para cachear assets estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}